[workspace]
resolver = "3"
members = [
    "crates/mapache",
    "crates/chunker",
    "crates/chunker/fuzz"
]

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
unwrap_used = "deny"
panic = "deny"
panic_in_result_fn = "deny"
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
undocumented_unsafe_blocks = "deny"

[workspace.package]
repository = "https://github.com/jlantxa/mapache"

[profile.dev]
opt-level = 1
debug = true

[profile.release]
strip = true
lto = true
codegen-units = 1
