[package]
name = "mapache"
version = "0.1.0"
edition = "2024"
rust-version = "1.88.0"


[profile.dev]
opt-level = 3


[dependencies]
aes-gcm-siv = "0.11.1"
anyhow = "1.0.98"
argon2 = "0.5.3"
base64 = "0.22.1"
blake3 = "1.8.2"
chrono = { version = "0.4.41", features = ["serde"] }
clap = { version = "4.5.40", features = ["derive", "wrap_help"] }
colored = "3.0.0"
crossbeam-channel = "0.5.15"
ctrlc = "3.4.7"
dialoguer = "0.11.0"
fastcdc = "3.2.1"
filetime = "0.2.25"
indicatif = { version = "0.18.0", features = ["rayon"] }
num_cpus = "1.17.0"
num_enum = "0.7.4"
parking_lot = "0.12.4"
rand = "0.9.1"
rayon = "1.10.0"
secrecy = "0.10.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
ssh2 = { version = "0.9.5", features = ["vendored-openssl"] }
zstd = "0.13.3"

[target.'cfg(unix)'.dependencies]
fuser = "0.15.1"
libc = "0.2.174"

[dev-dependencies]
tar = "0.4.44"
tempfile = "3.20.0"
xz2 = "0.1.7"
