[package]
name = "mapache"
version = "0.3.0"
edition = "2024"
rust-version = "1.91"
description = "Deduplicating encrypted backup tool"
license = "GPL-3.0-only"
repository.workspace = true

[dependencies]
aes-gcm-siv = "0.11.1"
anyhow = "1.0.102"
argon2 = "0.5.3"
async-stream = "0.3.6"
async-trait = "0.1.89"
blake3 = "1.8.5"
chrono = { version = "0.4.44", features = ["serde"] }
chunker = { path = "../chunker" }
clap = { version = "4.6.1", features = ["derive", "wrap_help", "env"] }
clap_complete = "4.6.5"
colored = "3.1.1"
conflate = "0.3.3"
crossbeam-channel = "0.5.15"
crossterm = { version = "0.29", optional = true }
dashmap = "6.2.1"
filetime = "0.2.29"
futures = "0.3.32"
indicatif = "0.18.4"
libc = { version = "0.2.186" }
parking_lot = "0.12.5"
rand = "0.10.1"
ratatui = { version = "0.30", optional = true }
rayon = "1.12.0"
russh = { version = "0.61.0", default-features = false, features = [
  "flate2",
  "ring",
  "rsa",
] }
russh-sftp = "2.2.2"
rust-s3 = { version = "0.37.2", default-features = false, features = [
  "with-tokio",
] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
signal-hook-registry = "1.4.8"
tokio = { version = "1.52", features = [
  "rt",
  "rt-multi-thread",
  "macros",
  "net",
  "io-util",
  "time",
] }
tokio-stream = "0.1.18"
toml = "1.1.2"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["fmt"] }
url = "2.5.8"
zeroize = { version = "1.8.2", features = ["derive"] }
zstd = "0.13.3"

[target.'cfg(unix)'.dependencies]
fuser = { version = "0.17.0", optional = true, default-features = false }
xattr = "1.6.1"

[target.'cfg(target_os = "linux")'.dependencies]
tikv-jemallocator = "0.6.1"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [
  "Win32_Foundation",
  "Win32_Storage_FileSystem",
  "Win32_System_Console",
  "Win32_System_SystemInformation",
  "Win32_System_Threading",
] }

[dev-dependencies]
rstest = "0.26.1"
scopeguard = "1.2.0"
tar = "0.4.46"
tempfile = "3.27.0"
xz2 = "0.1.7"

[features]
default = ["fuse"]
fuse = ["fuser"] #FUSE for mount command
tui = ["dep:ratatui", "dep:crossterm"]
