[package]
name = "mapache"
version = "0.1.8"
edition = "2024"
rust-version = "1.91"

[dependencies]
aes-gcm-siv = "0.11.1"
anyhow = "1.0.101"
argon2 = "0.5.3"
base64 = "0.22.1"
blake3 = "1.8.3"
chrono = { version = "0.4.43", features = ["serde"] }
chunker = { path = "../chunker" }
clap = { version = "4.5.58", features = ["derive", "wrap_help"] }
clap_complete = "4.5.66"
colored = "3.1.1"
crossbeam-channel = "0.5.15"
dialoguer = "0.12.0"
directories = "6.0.0"
filetime = "0.2.27"
hostname = "0.4.2"
httpdate = "1.0.3"
indicatif = { version = "0.18.4", features = ["rayon"] }
libc = { version = "0.2.182" }
num_cpus = "1.17.0"
num_enum = "0.7.5"
parking_lot = "0.12.5"
rand = { version = "0.10.0", features = ["sys_rng"] }
rayon = "1.11.0"
rust-s3 = "0.37.1"
rustc-hash = "2.1.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
signal-hook = "0.4.3"
signal-hook-registry = "1.4.8"
ssh2 = { version = "0.9.5", features = ["vendored-openssl"] }
threadpool = "1.8.1"
tokio = { version = "1.49", features = ["rt", "rt-multi-thread", "macros"] }
zstd = "0.13.3"

[target.'cfg(target_os = "linux")'.dependencies]
fuser = { version = "0.16.0", optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
mimalloc = { version = "0.1.48", features = ["override"] }

[dev-dependencies]
rstest = "0.26.1"
tar = "0.4.44"
tempfile = "3.25.0"
xz2 = "0.1.7"

[features]
default = ["fuse"]
fuse = ["fuser"]   #FUSE for mount command
