[package]
name = "chunker"
version = "0.2.2"
publish = false
edition = "2024"
description = "FastCDC (Fast Content-Defined Chunking) implementation"
repository.workspace = true
license = "GPL-3.0-only"

[[bin]]
name = "chunker-lookup"
path = "src/bin/lookup_gen.rs"

[dependencies]
anyhow = "1.0.102"
blake3 = "1.8.5"
rand = "0.10.1"

[dev-dependencies]
rstest = "0.26.1"
