name: main

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check format
        run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clippy
        run: cargo clippy

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Test
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            cargo test -r --verbose --no-default-features
          else
            cargo test -r --verbose
          fi
